### ISSUE TITLE
修正抽奖用属性书可以购买的问题

### ISSUE THREAD

**Issue by windybirth** [windybirth/windy10v10ai#682]
![Image](https://github.com/windybirth/windy10v10ai/assets/3445793/d821ceef-c262-4986-802b-c7508279dcf3)

**Comment by DocterZed** [comment]
Hello, I am Dr. Zed on steam. The one who created 10v10 AI wars.

Could you please reduce the price of the normal attribute books? I think the 19999 gold is too much, it takes too long to farm most games. I liked the balance of the lottery tomes at 4800 gold, it allowed you to stay fighting and improving in the game, rather than farming the jungle for a long time.

- I think a reasonable price could be 10000 gold for one tome of 50 attributes.

- Even better would be to change it to 5000 gold for one tome of 25 attributes. That way you can upgrade more often while fighting, and don't have to farm so much.

- Also, if the price of tomes was reduced, the price of the tome of luoshu could be reduced to 33333 gold, which is a much more reasonable and attainable price for most games.

Thank you for you consideration.

**Comment by windybirth** [comment]
@DocterZed 
Thank you for your advice.
The attribute book was originally designed as an item to buy when money has nowhere to go in the later stage, but it might be more interesting to use him in the mid game.

This issue will be closed because bug is fixed, and I will consider about the item price in as a new topic.

Finally thank you for created 10v10 AI wars!
