### ISSUE TITLE
[FEATURE] Allow members to reset Skill points free on a monthly/weekly basis

### ISSUE THREAD

**Issue by dfyzb0** [windybirth/windy10v10ai#996]
**Bug type**

- [ ] Ability
- [ ] Item
- [ ] Hero
- [ ] Bot
- [ ] UI
- [ X ] Other

**Describe the Feature**
The current leveling system requires around 13,000 hours of gameplay to complete. One misclick when leveling can result in a waste of 10s to 100+ hours of gameplay. At level 13, the 1400 points required to reset the skill points equates to roughly 10 hours of gameplay. As a member, it is currently very demotivating to continue playing the game as you level up. The higher the level you are, the greater the punishment, the less the rewards, and the more work that is required. 

My suggestion is to allow paid members to reset their skill points once a week or once a month for free so they can try out different builds while they go through the endless grind that is currently in place for the leveling system. This would make the game more fun and motivate players to continue playing even when faced with an unobtainable leveling system.

**Expected behavior**
N/A

**To Reproduce**
N/A

**Screenshots**
N/A

**Comment by FruitAre** [comment]
This game mode is really not designed to be a infinite grind, soloing the highest difficultly is trivial on non-support characters once you get to 35 points and you could afford almost all of the attribute effects which aren't easily obtainable through other means, the extra levels add very little to game play when there are only self-imposed challenges left. I'm for easier points resets, as far as the back end would allow, since the viability of heroes varies a lot depending and what attributes you have. I would also like to bring your attention to two things about the points system:

2.33 battle points per minute is very much on the low end, you will naturally get points faster on higher difficulties, if you have 5 attribute levels per difficulty (10 for n6) it's hardly more difficult, if at all, since the bots having higher gold multiplier also increases the gold bounties for killing them, you could also employ very specific strategies to farm points and reach a little over 5 points per minute including loading time, but that isn't much fun imo.

While the cost per point increases, the absolute power increase you get from each point increases as well the more points you have, since many of the stats factor with each other e.g the effectiveness of 15 attack damage is multiplied by agility, attack speed, attack range, life-steal, while the effectiveness of the healing you get from life-steal is also multiplied by armor/magic resist and damage reduction, while cool down reduction, status resistance, and movement speed often come into play as well.

**Comment by dfyzb0** [comment]
@FruitAre we're at level 25 and the highest we can clear is N4. Are we doing something wrong? My friend and I just play 2v10. Granted most of our points are in movement speed, CDR, and life steal.

**Comment by windybirth** [comment]
FruitAre explained the original intention of the design.
The attribute system is not designed to be completed at full level.
You can imagine that this is a Roger like game. You can get stronger, but there is no limit. (Cannot get maxlevel)

**Comment by dfyzb0** [comment]
@windybirth If the system is not designed to be completed at full level, wouldn't it make more sense to allow members to reset their levels for free on a periodic basis? It would add an element of being able to try out different builds, which would encourage people to continue playing the game and continue to pay for the membership. With the current system, once you've achieved a certain level, it is no longer worth it to pay for the reset, the time investment is too large. If anything the current system encourages people to stop playing the game once they've reached a certain level because there is nothing left to earn and no way to change the game without losing a considerable amount of time investment.

**Comment by FruitAre** [comment]
Sorry for the somewhat delayed response, there aren't many options to play the game slower-paced if you only have two people and don't have the %incoming damage reduction attribute for a front line. Movement speed and Cooldown reduction are both useful, life steal is okay but only the heroes with the biggest physical damage steroids can use it well lategame (Shadow Fiend, Drow, PA).

Black King Bar is practically mandatory as the enemy buys de-buffing and CC items, take Eye of Skadi upgrade for example, after the massive heal reduction and attack speed reduction, your life steal will hardly do anything.

As stated in my earlier post, the bots increased net worth means you get a much larger bounty for killing them, you want to complete as many items as possible before the bots start grouping up as 10, and to kill barracks in all 3 lanes is easier than going for the ancient on the higher difficulties.

An example strat to kill the bots as fast as possible would be 1 ranged/ Marci or Lycan
ranged goes Hand of Midas WraithBandx2 > Power Threads Hand of team> Infernal Desolator Wings of Haste > Gold Pike> BKB> Excalibur
melee Hand of Midas WraithBand or Bracerx2 > Power Threads Hand of team> Assault Vladimir Wings of Haste > BKB> Whatever
Easiest to repeat kill mid and farm jungle until you get the -30 armor reduction, then repeat kill side lanes as well until you are strong enough to kill their base.

If you don't have %incoming damage reduction attribute you have to resort to cheesier strategies to not get outscaled. There are a bunch you can figure out if you theorycraft.

**Comment by windybirth** [comment]
Thanks for you discussion. I reconsidered it and I think 'add an element of being able to try out different builds' is impotent.
I have some ideas but not easy to implement.
Anyway, thanks for making me realize this.

**Comment by dfyzb0** [comment]
@FruitAre Thanks for the advice. I'm focusing on DR now and it is helping!

@windybirth Thanks for reconsidering! It would be fun if once a week, or every other week, you could use a free reset. Then players could spend the next week or two playing heroes that work well with the way they rebuilt their profile (for example, allocating their points in a way that would specifically benefit INT spell casters on week, then ranged agility the next week)
